apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blueappdep
  name: blueappdep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blueappdep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blueappdep
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
