apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: lnd-nginx-dep
  name: lnd-nginx-dep
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lnd-nginx-dep
  type: NodePort
status:
  loadBalancer: {}
