apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lnd-nginx-dep
  name: lnd-nginx-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: lnd-nginx-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lnd-nginx-dep
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
